const data = {
  products: [
    {
      name: "skinny slim cottton shirt",
      slug: "Jeans cotton",
      category: "Trousers",
      image: "/images/p1.jpg",
      price: 10,
      countInStock: 10,
      brand: "Cooper",
      rating: 2,
      numReviews: 10,
      description: "jeans for daily wear",
    },
    {
      name: "tshirt cottton",
      slug: "tshirt cotton",
      category: "tshirt",
      image: "/images/p2.jpg",
      price: 20,
      countInStock: 10,
      brand: "Cooper",
      rating: 2,
      numReviews: 10,
      description: "tshirt for daily wear",
    },
    {
      name: "Pants cottton",
      slug: "Pants cotton",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 30,
      countInStock: 10,
      brand: "Cooper",
      rating: 2,
      numReviews: 10,
      description: "Pants for daily wear",
    },
    {
      name: "Innerwear cottton",
      slug: "Innerwear cotton",
      category: "Innerwear",
      image: "/images/p4.jpg",
      price: 40,
      countInStock: 10,
      brand: "Cooper",
      rating: 2,
      numReviews: 10,
      description: "Innerwear for daily wear",
    },
  ],
};
export default data;